git:
  commitMessage: "release: v${version}"
  tagName: "v${version}"
  requireCleanWorkingDir: true
  push: true
  tag: true

hooks:
  before:release: "yarn build"

github:
  release: false

npm:
  publish: false

plugins:
  "@release-it/conventional-changelog":
    preset: "conventionalcommits"
    infile: "CHANGELOG.md"
    ignoreRecommendedBump: true
    strictSemVer: true
